package sample.app.gallery.ksp

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.processing.KSPLogger
import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.processing.SymbolProcessor
import com.google.devtools.ksp.symbol.KSAnnotated
import com.google.devtools.ksp.symbol.KSFunctionDeclaration
import java.io.File

private const val ANNOTATION = "sample.app.gallery.GalleryExample"
private const val GENERATED_PACKAGE = "sample.app.gallery.generated"
private const val GENERATED_OBJECT = "GallerySources"

/**
 * Reads back the source of every `@GalleryExample` composable and emits it as a
 * `const val` on [GENERATED_OBJECT], so the sample app can display — and let the
 * user copy — the exact code that produced the preview next to it.
 */
class GalleryProcessor(
    private val codeGenerator: CodeGenerator,
    private val logger: KSPLogger,
) : SymbolProcessor {

    private var invoked = false

    override fun process(resolver: Resolver): List<KSAnnotated> {
        if (invoked) return emptyList()
        invoked = true

        val symbols = resolver.getSymbolsWithAnnotation(ANNOTATION)
            .filterIsInstance<KSFunctionDeclaration>()
            .toList()
        if (symbols.isEmpty()) return emptyList()

        val sources = sortedMapOf<String, String>()
        for (function in symbols) {
            val name = function.simpleName.asString()
            val path = function.containingFile?.filePath
            if (path == null) {
                logger.warn("No source file for @GalleryExample $name", function)
                continue
            }
            val body = extractFunctionBody(File(path).readText(), name)
            if (body == null) {
                logger.warn("Cannot extract the body of @GalleryExample $name", function)
                continue
            }
            // Names become `const val`s on a single object, so collisions would
            // silently drop one of the two examples.
            sources.put(name, body)?.let {
                logger.error("Duplicate @GalleryExample name: $name", function)
            }
        }
        if (sources.isEmpty()) return emptyList()

        val code = buildString {
            appendLine("// GENERATED by :sample:galleryKsp — do not edit")
            appendLine("package $GENERATED_PACKAGE")
            appendLine()
            appendLine("internal object $GENERATED_OBJECT {")
            for ((name, body) in sources) {
                appendLine("    const val $name: String = \"\"\"${escapeForRawString(body)}\"\"\"")
            }
            appendLine("}")
        }

        codeGenerator.createNewFile(
            dependencies = Dependencies(
                aggregating = true,
                sources = symbols.mapNotNull { it.containingFile }.toTypedArray(),
            ),
            packageName = GENERATED_PACKAGE,
            fileName = GENERATED_OBJECT,
        ).use { it.write(code.toByteArray()) }

        return emptyList()
    }
}

/**
 * Returns the dedented content between the outer braces of [functionName], or
 * `null` when the function cannot be located. Skips over string/char literals
 * and comments so braces inside them do not unbalance the scan.
 */
internal fun extractFunctionBody(source: String, functionName: String): String? {
    val declaration = Regex("""fun\s+$functionName\s*\(""").find(source) ?: return null

    // Step over the parameter list before looking for the body brace, so a
    // trailing-lambda default value is not mistaken for the opening brace.
    var i = declaration.range.last + 1
    var parens = 1
    while (i < source.length && parens > 0) {
        when (source[i]) {
            '(' -> parens++
            ')' -> parens--
        }
        i++
    }
    i = source.indexOf('{', startIndex = i)
    if (i < 0) return null

    val bodyStart = ++i
    var depth = 1
    val length = source.length
    while (i < length && depth > 0) {
        when {
            source.startsWith("\"\"\"", i) -> {
                val end = source.indexOf("\"\"\"", i + 3)
                i = if (end < 0) length else end + 3
                continue
            }
            source[i] == '"' || source[i] == '\'' -> {
                val quote = source[i++]
                while (i < length && source[i] != quote) {
                    if (source[i] == '\\') i++
                    i++
                }
                i++
                continue
            }
            source.startsWith("//", i) -> {
                val end = source.indexOf('\n', i)
                i = if (end < 0) length else end
                continue
            }
            source.startsWith("/*", i) -> {
                val end = source.indexOf("*/", i + 2)
                i = if (end < 0) length else end + 2
                continue
            }
            source[i] == '{' -> depth++
            source[i] == '}' -> depth--
        }
        if (depth > 0) i++
    }
    if (depth != 0) return null

    return dedent(source.substring(bodyStart, i))
}

/** Drops the surrounding blank lines and the indentation shared by every line. */
private fun dedent(text: String): String {
    val lines = text.lines().dropWhile { it.isBlank() }.dropLastWhile { it.isBlank() }
    if (lines.isEmpty()) return ""
    val indent = lines.filter { it.isNotBlank() }
        .minOf { it.length - it.trimStart().length }
    return lines.joinToString("\n") { if (it.isBlank()) "" else it.drop(indent) }
}

/**
 * Neutralises the two sequences a Kotlin raw string cannot carry verbatim: the
 * template `$` and the closing `"""`.
 */
private fun escapeForRawString(text: String): String = text
    .replace("$", "\${'$'}")
    .replace("\"\"\"", "\"\"\${'\"'}")
